### ISSUE TITLE
Dependency App

### ISSUE THREAD

**Issue by meatballs** [theref/web3auth-anvil#2]
To make this app a proper dependency, we need to change how the js is injected (and probably some css later) because native libraries only work from a 'parent' app and not from a dependency.

Anvil Extras has already solved this problem and has some utilities for doing so: 

https://github.com/anvilistas/anvil-extras/blob/main/client_code/utils/_component_helpers.py

Which gives us a choice of the way forward:

1. Make Anvil Extras a dependency of this app and then use its helpers module
1. Add this component to Anvil Extras and drop this repo
1. Take the helpers module in its entirety, add it to this app and use it (It's on the MIT licence, so that's fine as long as we include the licence text).
1. Do our own thing to inject the js/css within this app

Anyone got a preference?

**Comment by theref** [comment]
Not sure I fully appreciate the pros/cons of each of the options to be honest

**Comment by meatballs** [comment]
1 feels like a recipe for dependency hell
2 depends if you want to keep this repo or submit code to anvil extras
I'd go for three over four.

So, two or three for me.

**Comment by meatballs** [comment]
How about we go for three? We can always opt for two later, if we want.
